### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by rafael-glima** [cshelton/hawkesinf#2]
Dear Shelton,

I tried to compile the code after installing the libboost-dev in my Ubuntu 18.04 laptop, but I keep getting the following error:

**g++ --std=c++1y -O3 -o timetst timetst.cpp -L/usr/local/lib -lboost_program_options -lrt
In file included from plottraj.hpp:4:0,
                 from timetst.cpp:1:
gnuplot-cpp/gnuplot_i.hpp: In destructor ‘Gnuplot::~Gnuplot()’:
gnuplot-cpp/gnuplot_i.hpp:1021:74: warning: throw will always call terminate() [-Wterminate]
         throw GnuplotException("Problem closing communication to gnuplot");
                                                                          ^
gnuplot-cpp/gnuplot_i.hpp:1021:74: note: in C++11 destructors default to noexcept
/usr/bin/ld: cannot find -lboost_program_options
collect2: error: ld returned 1 exit status
Makefile:8: recipe for target 'timetst' failed
make: *** [timetst] Error 1**

I already tried adding a symbolic link to the package, but it is still not working. Is there any recommended Ubuntu version with which I should try the code?

Best regards,

**Comment by cshelton** [comment]
Sorry, I didn't see this until now.  The warning is not a problem.  It looks like you are missing the Program Options part of the boost library.  I think you need to install the "libboost-program-options-dev" package on your laptop.

**Comment by cshelton** [comment]
Seems to have been resolved.
